micronaut:
  application:
    name: micronaut-liquibase-graal
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/users
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: secret
    schema-generate: NONE
    dialect: MYSQL
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
---
endpoints:
  liquibase:
    enabled: true
    sensitive: false
