micronaut:
  application:
    name: micronaut-liquibase-graal
datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/users'
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret
    schema-generate: none
    dialect: POSTGRES
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
---
endpoints:
  liquibase:
    enabled: true
    sensitive: false
